### ISSUE TITLE
em's or rem's instead of px?

### ISSUE THREAD

**Issue by zenopopovici** [jkphl/grunt-svg-sprite#21]
Hey,

Would it be possible to specify sizes in em's or rem's? 
I would make things easier with responsive sites.

In theory, the sprite (along with the icons) should resize without a hitch on font-size changes on the body element.

Zeno.

**Comment by dildeeplehal** [comment]
I'm trying to do this too, but i don't know how to call the mustache template in my grunt configuration. I can't see in the docs what the option is. Any help or just a paste of the grunt config may do it?

**Comment by jkphl** [comment]
Hey @dildeeplehal,

depending on your setup, the option will be something like

```javascript
mode.css.render.less {
    template: 'path/to/your/template.less',
    dest: 'result/name/and/path.less'
}
```

Please [see here](https://github.com/jkphl/svg-sprite#e-rendering-configurations) for more info on rendering configurations (and bear in mind that the configuration has completely changed since @zenopopovici asked this).

**Comment by dildeeplehal** [comment]
Thanks, I've managed to get it calling my template. Now i need to work out what needs to go in that template so it's in EM units. Where is the documentation for the templating variables so i can work out what to do: I saw this in your files:

{{#shapes}}{{#selector.shape}}.{{#classname}}{{expression}}{{/classname}}{{^last}},
{{/last}}{{/selector.shape}} {
	background-position: {{position.relative.xy}};
	background-repeat: no-repeat;
	background-image: url({{{sprite}}});
	width: {{width.outer}}px;
	height: {{height.outer}}px;
}
{{/shapes}}

I want to make the background-positon and width/height in ems so to make this responsive.

**Comment by jkphl** [comment]
Hey @dildeeplehal,

please be aware that as of the 1.x release, *svg-sprite* uses percentages for placing the background images. They should be perfectly responsive out of the box. I don't see any advantage in rewriting it to use `em`s. If you insist on doing so, you would have to tinker with the `position.{relative|absolute}.{x|y|xy}` values. The documentation for the available variables can be found [here](https://github.com/jkphl/svg-sprite#f-templating-variables) (next time, you might just want to use the [README](https://github.com/jkphl/grunt-svg-sprite/blob/master/README.md) to find it).

Cheers,
Joschi

**Comment by dildeeplehal** [comment]
Thanks again, i found it eventually.

But still, the background-position uses percentages, but the width and height are set using px, so i cant resize them responsively.

**Comment by jkphl** [comment]
Sure you can. Please see [this internal test page](https://rawgit.com/jkphl/svg-sprite/master/test/fixture/html/sprite/weather-svg.html) under the "Relative (%)" section.

**Comment by zenopopovici** [comment]
I've updated it for the current version. Configuration for LESS:

## Grunt File

```
		svg_sprite: {
			less_sprite : {
				expand: true,
				cwd: 'assets/images/svg',
				src: ['*.svg'],
				dest: 'assets/images/',
				options: {
					mode: {
						css: {
							bust: false,
							dest: '',
							common: '',
							prefix: 'svg-',
							sprite: 'sprite.svg',
							render: {
								less: {
									template: 'sprite-mustache.less',
									dest: 'sprite.less'
								}
							}
						}
					}
				}
			}
		},
```

## The Mustache Template
```
.{{mixin}}{{^common}}(){{/common}} {
	background-repeat: no-repeat;
	background-image: url({{{sprite}}});
}

{{#shapes}}{{#selector.shape}}{{expression}}{{^last}},
{{/last}}{{/selector.shape}} {
	background-position: {{position.relative.xy}};{{^common}}
	.{{mixin}}();{{/common}}{{#dimensions.inline}}
	width: {{width.outer}} * @rem;
	height: {{height.outer}} * @rem;{{/dimensions.inline}}
}{{#dimensions.extra}}

{{#selector.dimensions}}{{expression}}{{^last}},
{{/last}}{{/selector.dimensions}} {
	width: {{width.outer}} * @rem;
	height: {{height.outer}} * @rem;
}{{/dimensions.extra}}

{{/shapes}}
```

## Vars for conversion

```
@base-font-size: 100%;

@base-font-size-px: 16;
@rem: (1 / @base-font-size-px) + 0rem;
```

**Comment by zenopopovici** [comment]
Anyway. Just great work. I use it for all my projects. ;)

**Comment by jkphl** [comment]
Thanks a lot for sharing this, @zenopopovici! :+1:

**Comment by zenopopovici** [comment]
@dildeeplehal here's the config for SASS if you really want to use ems/rems:

Drop this in your mixins file:
```
@function em($target, $context: $base-font-size) {
   @if $target == 0 { @return 0 }
   @return $target / $context + 0em;
}
$base-font-size: 16px;
```

Modify your Mustache template like this:

````
.{{mixin}}{{^common}}(){{/common}} {
    background-repeat: no-repeat;
    background-image: url({{{sprite}}});
}

{{#shapes}}{{#selector.shape}}{{expression}}{{^last}},
{{/last}}{{/selector.shape}} {
    background-position: {{position.relative.xy}};{{^common}}
    .{{mixin}}();{{/common}}{{#dimensions.inline}}
    width: em({{width.outer}});
    height: em({{height.outer}});{{/dimensions.inline}}
}{{#dimensions.extra}}

{{#selector.dimensions}}{{expression}}{{^last}},
{{/last}}{{/selector.dimensions}} {
    width: em({{width.outer}});
    height: em({{height.outer}});
}{{/dimensions.extra}}

{{/shapes}}
````

I haven't tested it but it should to the trick.

**Comment by zenopopovici** [comment]
@jkphl sure thing :)

**Comment by dildeeplehal** [comment]
Thanks for your help guys. I've implemented that. Had to change some stuff in the mustache template to get it to work in sass and it has basically done what i wanted to do now. Needs a bit of refining but on the right track now. It was tough getting around the Mustache syntax because i'm not familiar with that. :)

**Comment by jkphl** [comment]
Glad it works for you now! :)
