### ISSUE TITLE
cleanconfig deprecated ?

### ISSUE THREAD

**Issue by miguelmoraleda** [jkphl/grunt-svg-sprite#26]
Hey,

I'm implementing the last release on a project, but I can't find the way to config the clean function. Is it deprecated?

I was using the example below:

```js
cleanconfig: {
plugins: [
{ removeViewBox: false },
{ removeUselessStrokeAndFill: false },
{ cleanupIDs: false },
{ mergePaths: false }
]
},
```

**Comment by jkphl** [comment]
Hi @miguelmoraleda,

I guess you answered your own question in the meantime, right? Happy spriting anyway! :)

Cheers,
Joschi

**Comment by jkphl** [comment]
@miguelmoraleda btw, please don't wipe out the issues fields — this makes it pretty impossible to reconstruct the issue history. Thanks! :+1:

**Comment by miguelmoraleda** [comment]
Hi @jkphl,

You are right. Sorry about the wipe :).

I'm running in a new problem... SVGO is adding a letter to each of my IDs. Do you have any idea how to avoid this behaviour?

Thanks in advance.

Best regards,

Miguel

**Comment by jkphl** [comment]
It's not SVGO adding the letter, but *svg-sprite* itself. To avoid possible ID conflicts while combining multiple SVG files into a sprite, the IDs need to get "namespaced", which is done by prepending them with a (unique) letter. Otherwise ID clashes could happen ...

**Comment by jkphl** [comment]
(This isn't something new, by the way, has been the same with previous *svg-sprite* releases)

**Comment by jkphl** [comment]
I could imagine making the namespacing optional, however. In that case, you would have to avoid ID clashes manually. Interested in this? I could try to do this tomorrow (it's 2:30 a.m. over here, definitely time for going to bed ;)). Cheers, Joschi

**Comment by miguelmoraleda** [comment]
Yeah!! I'm very interested on it. I would be grateful if you can add namespacing as optional. In my current flow I have a "src" svg folder and a "dest" svg folder for my sprite... In the src folder I'm adding IDs to specific paths, so I can animate it later. The namespacing scary me a little bit because my IDs can change the name every time I regenerate the sprite.

Have a nice rest and thank you for a great work :)

Best regards,

Miguel

**Comment by jkphl** [comment]
Closing this in favour of #27.

**Comment by jkphl** [comment]
Hey @miguelmoraleda,

as of [release v1.0.6](https://github.com/jkphl/grunt-svg-sprite/tree/v1.0.6) *grunt-svg-sprite* now supports disabling ID namespacing. Please see the [`namespaceIDs` option](https://github.com/jkphl/svg-sprite#c-common-svg-options) for further details.

Cheers,
Joschi

**Comment by miguelmoraleda** [comment]
Hey @jkphl,

Thank you!!! :)
