### ISSUE TITLE
Fatal error: path must be a string when setting css mode options

### ISSUE THREAD

**Issue by daltonridenhour** [jkphl/grunt-svg-sprite#30]
I'm getting "Fatal error: path must be a string" when I add any additional options to the css mode:

    mode            : {
         css         : {     // Activate the «css» mode
             render  : {
                  css : true,
                  layout : 'horizontal'
             }
        }
    }

Any ideas?  Thanks!

**Comment by jkphl** [comment]
Hi @daltonridenhour,

that one is easy: the `layout` option is one level too deep. Make it a sibling of `render` and you should be fine:

```js
mode            : {
     css         : {     // Activate the «css» mode
         layout : 'horizontal'
         render  : {
              css : true,
              
         }
    }
}
```

Works for you?

Cheers,
Joschi

**Comment by daltonridenhour** [comment]
Ah!  Misread the docs.  Thanks!  This is a great plugin.

**Comment by jkphl** [comment]
Glad you like it, thanks! :+1:

**Comment by daltonridenhour** [comment]
Actually, while you are here, is there a way to apply only padding-bottom to the icons in a horizontal layout?  I want to be able to pad the icons and still use background-size: cover to make it completely fill the container dimensions.
