### ISSUE TITLE
What means \: ?

### ISSUE THREAD

**Issue by nicksyndicate** [jkphl/grunt-svg-sprite#33]
After generation see this code

```
.i-weather-storm:hover,
.i-weather-storm\:hover
```

What means this ``` \: ``` ?

**Comment by nicksyndicate** [comment]
Plz close issue. I mistaked repository.

**Comment by jkphl** [comment]
Pls read [this thread](https://github.com/jkphl/gulp-svg-sprite/issues/9) for an explanation.
