### ISSUE TITLE
Custom output filenames/paths?

### ISSUE THREAD

**Issue by scottastrophic** [jkphl/grunt-svg-sprite#34]
Does the Advanced Features documentation pointing to the main svg-sprite repo mean that those features are currently not accessible via options specified in the Gruntfile? I can't see anywhere in https://github.com/jkphl/grunt-svg-sprite/blob/master/tasks/svg_sprite.js that would provide a hook to change the output names and paths, but I wanted to make sure I'm not missing something. Thanks!

**Comment by jkphl** [comment]
Hi @scottastrophic,

it's exactly the other way round: As [stated in the grunt-svg-sprite docs](https://github.com/jkphl/grunt-svg-sprite#options), you can pass **all of the svg-sprite options** as `options` to your Grunt task (have a look at the [basic example](https://github.com/jkphl/grunt-svg-sprite#basic-example)). Maybe [this](https://github.com/jkphl/svg-sprite/blob/master/docs/grunt-gulp.md) also clarifies a bit?!

Cheers,
Joschi

**Comment by jkphl** [comment]
Oh, and maybe you'd want to use the [brand new online configurator](http://jkphl.github.io/svg-sprite) to kickstart your Gruntfile? (Very early stage, feedback welcome!)

**Comment by scottastrophic** [comment]
The configurator proved super useful for figuring out exactly what I needed to do (change "true" to a configuration object). It's just about perfect, thanks very much.

**Comment by jkphl** [comment]
Thanks. You're very welcome! :)
