### ISSUE TITLE
Mulitple src folders

### ISSUE THREAD

**Issue by tolvstein** [jkphl/grunt-svg-sprite#36]
Reposting in the correct project, sorry :)

Would it be possible to somehow set multiple src folders likes this:

src: [
'common/images/svg/',
'project1/images/svg/'
]

As it is right now, the script only handles the first src param and ignores the second one. I have multiple subprojects in which I would like to have both common svgs (used in multiple projects) and project specific svgs in different folders.

**Comment by jkphl** [comment]
Hey @tolvstein,

thanks! ;)

I'll see what I can do about it. :+1:

Cheers,
Joschi

**Comment by jkphl** [comment]
@tolvstein I just did a quick test. Are you sure that you are working with the latest version of *grunt-svg-sprite*? Having multiple source directories seems to work just fine for me (with and without `cwd` argument). Could you please post your complete Grunt task? Thanks!

**Comment by jkphl** [comment]
@tolvstein Any progress on this?

**Comment by jkphl** [comment]
@tolvstein I'll close this for now. Please feel free to reopen the issue in case you still got problems.
