### ISSUE TITLE
Console error message missing when sprite compilation failed

### ISSUE THREAD

**Issue by tkoomzaaskz** [jkphl/grunt-svg-sprite#38]
Currently, when you've got an error in your grunt config which will lead to compilation error, you will see that everything is alright and it's misleading:

    Tomasz.Ducin@WAWLT548 ~/Tests/svg-sprite-test
    $ grunt --force
    Running "svg_sprite:basic" (svg_sprite) task

    Running "svg_sprite:basic2" (svg_sprite) task

    Running "svg_sprite:flags" (svg_sprite) task

    Done, without errors.

And the truth is that `spriter.compile(function(error, result) { ... }` throws an error in fact. Currently, it is handled in the following way:

    if (error) {
    
    } else {

which I find a very bad solution. I suggest to provide a standard grunt fail output so that the developer at least knows, that something is wrong with his configuration (e.g. [grunt.fail](http://gruntjs.com/api/grunt.fail#grunt.fail.warn)).

**Comment by tkoomzaaskz** [comment]
The solution for this is done in #39.

**Comment by jkphl** [comment]
Hey @tkoomzaaskz,

awesome — thanks for this contribution. I must have overseen that I never finished that one! :+1:

Cheers,
Joschi
