### ISSUE TITLE
Make sprite url configurable

### ISSUE THREAD

**Issue by stefanjudis** [jkphl/grunt-svg-sprite#4]
Hey Joschi,

currently the .scss file points to a generated url.

Maybe I'm missing a config option, but I would like to set up the path myself, because it's not matching with my setup.

```
%svg {
    background-image:url(svg/sprite.svg); // this path is configurable???
    background-repeat:no-repeat
}
```

Thanks a lot.

**Comment by extractachris** [comment]
I'm struggling to make this work. Here is what I have:

```
your_target: {
  expand: true,
  cwd: '<%= appDir %>assets/img/svg',
  src: ['**/*.svg'],
  dest: '<%= appDir %>assets/img/sprite',
  options: {
    mode: {
      css: {
        sprite: 'sprite.svg',
        spritedir: '../../../img/sprite',
        bust: false,
        dimensions: true,
        prefix: '.icon-',
        render: {
          scss: {
            dest: '../../../scss/_svg-sprite.scss'
          }
        }
      }
    }
  }
}
```

**Comment by jkphl** [comment]
Hey @extractachris,

it looks like you're mixing configuration options of the old and the current version of *sprite-svg*. Please look at the [relevant section in the docs](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties). There is no option `mode.<mode>.spritedir` (anymore?), only `mode.<mode>.sprite`. Also, the section about [output destinations](https://github.com/jkphl/svg-sprite/blob/master/README.md#output-destinations) could be of interest for you. Finally, maybe you could consider using the [online configurator / kickstarter](http://jkphl.github.io/svg-sprite) to get your config fixed?!

Please let me know if you get along!

Cheers, Joschi

**Comment by extractachris** [comment]
:thumbsup:

Thank you!
