### ISSUE TITLE
Changing created directory's

### ISSUE THREAD

**Issue by myurtsev** [jkphl/grunt-svg-sprite#42]
Hi,

Is there an option to prevend the creation of the 'view' and 'svg' directory? Right now it is automaticly saved in 'view/svg/sprite.view.svg' I just want the sprite.view.svg placed in the dest directory.

Another question :) Can I name it to?

Basically I want to name and save the created sprite and css where I want to. Hope you can help.

Thanks!

**Comment by PeterMK85** [comment]
Hello @myurtsev,

Check this out:

    example: {
           expand: true,
            cwd: '<%= yeoman.app %>/images/example/design/sprites-vector',
            src: ['**/*.svg'],
            dest: '<%= yeoman.app %>/',
            options: {
                mode: {
                    css: {
                        prefix: '%example-%s',
                        dest: 'styles/example', //scss destination
                        sprite: '../../images/example/design/example-sprite.svg', //Sprite destination and name
                        bust: false,
                        render: {
                            scss: {
                                dest: '_example-sprite.scss' //scss name
                            }
                        }
                    }
                }
            }
       }

**Comment by jkphl** [comment]
Thanks for helping out, @PeterMK85! :)

@myurtsev: Yes, there are config options for all of these. Basically, you need to set the [main output directory](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#main-output-directory) `dest`, the [mode output directory](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties) `mode.view.dest` and the sprite path and name `mode.view.sprite` accordingly. In your case, you will probably want something like tthis:

```js
var config = {
     dest: 'your/output/dir',
     mode: {
          view: {
               dest: '.',
               sprite: 'whatever-you-want.svg'
          }
     }
}
```

**Comment by myurtsev** [comment]
Thank you @jkphl and @PeterMK85 really helpfull! But is it also possible to change the background position in pixels instead of percentages.

**Comment by jkphl** [comment]
Yes, you can always author your own Mustache template and use the absolute position values instead. However, switching to relative positioning (and thus **making the positioning responsive**) was one of the major improvements of the new *svg-sprite* generation. Why would you want absolute positioning?
