### ISSUE TITLE
I'm having cwd issues

### ISSUE THREAD

**Issue by stevenalanstark** [jkphl/grunt-svg-sprite#44]
Hello,

This is working without using cwd, but when I try to use cwd the path is partially duplicated. I'm unable to determine why this is happening.

grunt options:

    svg_sprite: {
      client: {
        expand: true,
        cwd: 'client/public/svgs/',
        src: ['**/*.svg'],
        dest: 'client/public/out/',
        options: {
          mode: {
            css: {
              render: {
                css: true
              }
            }
          }
        }
      }
    },

but when I run it, I get the following error:

    $ grunt svg_sprite:client
    Running "svg_sprite:client" (svg_sprite) task
    >> Source file "c:\projects\gtp\client\public\svgs\client\public\svgs\mgk_vector_logo.svg" not found.

as you can read in the error, it's duplicating the 'client\public\svgs\' part of the path, which is a mistake.

Am I doing something wrong, or is this a bug?

thank you,

~Steven

**Comment by jkphl** [comment]
Looks like this has been a Windows specific bug. Fixed with [release v1.1.2](https://github.com/jkphl/grunt-svg-sprite/releases/tag/v1.1.2). Cheers, Joschi
