### ISSUE TITLE
Task done, but without sprite svg

### ISSUE THREAD

**Issue by LeG3nDz** [jkphl/grunt-svg-sprite#45]
Hi,

I test your plugin for generate svg sprite, but after start task svg_sprite, I have no output file.

My code :

    svg_sprite                  : {
        basic                   : {

            // Target basics
            expand              : true,
            cwd                 : 'images/svg/*.svg',
            src                 : ['images/svg/*.svg'],
            dest                : 'out'
        }
    }

I've 'images/svg' folders with my all icons svg.

Can you help me ?

Thank you :)

**Comment by jkphl** [comment]
Hi @LeG3nDz,

without having tested it: You should get rid of that `*.svg` in your `cwd` setting ("**c**urrent **w**orking **directory**"). Please let me know if that works for you.

Cheers,
Joschi

**Comment by LeG3nDz** [comment]
Yop,

Thak you for response. I've test without "*.svg", but no result :

    svg_sprite : {
        basic : {
            expand              : true,
            cwd                 : 'images/svg',
            src                 : ['images/svg/*.svg'],
            dest                : 'out'
        }
    }

**Comment by jkphl** [comment]
Ok, seems like there's still an error that I didn't spot in the first place. Please have a look at the example config from the docs:

```javascript
your_target: {
    expand      : true,
    cwd         : 'path/to/assets',
    src         : ['**/*.svg'],
    dest        : 'path/to/css/dir',
    options     : {
        // Target-specific options
    }
},
```

The `cwd` setting specifies the working directory, while the `src` settings specifies the glob within the `cwd`. So your setup would look for SVGs like `images/svg/images/svg/*.svg`. Please modify your `src` setting accordingly.

Cheers,
Joschi

**Comment by jkphl** [comment]
Hi @LeG3nDz,

did you have the chance to test this again with a corrected `svg` setting? Any progress on this? Thanks!

Cheers, Joschi

**Comment by LeG3nDz** [comment]
Hi @jkphl 

Yep, with your past post, it's okay :)

Thank you !

**Comment by jkphl** [comment]
Good to know, and glad it works for you! Cheers!
