### ISSUE TITLE
Seperator does not change

### ISSUE THREAD

**Issue by burakhanalkan** [jkphl/grunt-svg-sprite#51]
Hi,
I generated css outputs by using your plugin with the configuration settings which are below. However, still seperator is generated with double line  
(.icon-content--application--images--icon-set--edit-gray)

Also, when i try to leave prefix as  "prefix: '.icon-'" still folder path is added.

svg_sprite: {
            basic: {
                expand: true,
                cwd: 'ReponsiveWeb',
                src: ['content/application/images/icon-set/*.svg'],
                dest: 'content/application/images/icons/sprite-icons',
                shape: {
                    id: {
                        separator: '-',
                        generator: 'sprite'
                    },
                    dimension:{
                        maxWidth: 50,
                        maxHeight: 50,
                        attributes: true
                    },
                    spacing: {
                        padding: 10
                    }
                },
                options: {
                    mode: {
                        css: {
                            prefix: '.icon-',
                            render: {
                                css: true,
                                less: true
                            }
                        }
                    }
                }
            }
        }

Thank yo for your helping.

**Comment by jkphl** [comment]
Without having tested it, please try writing `separator` instead of `seperator` ;)

Cheers, Joschi

**Comment by burakhanalkan** [comment]
Hi,

In the code that part is true :)
But i found the mistake, shape config part must be inside of options. When i try as below it worked.

 options: {
                    shape: {
                        id: {
                            separator: '-',
                            generator: 'sprite'
                        },
                        dimension: {
                            maxWidth: 50,
                            maxHeight: 50,
                            attributes: true
                        },
                        spacing: {
                            padding: 10
                        }
                    },
                    mode: {
                        css: {
                            common: 'sprite-icons',
                            prefix: '.icon-',
                            render: {
                                css: true,
                                less: true
                            }
                        }
                    }
                }
