### ISSUE TITLE
Change % based with declaration px based one

### ISSUE THREAD

**Issue by PeterMK85** [jkphl/grunt-svg-sprite#52]
Due to different devices transforms % into different px values it would be better to use px based ones.

Exact defect:
+ On IPhone 4 or Internet Exporer 11 on win, the plugin generated %based size is totally different than a Chrome on win.
(also a possibility to make this optional)

**Comment by jkphl** [comment]
Well, switching from absolute (pixels) to relative (percent) positioning was one of the major improvements of the latest *svg-sprite* generation, essentially enabling responsive use of the sprites. I didn't run into problems with this so far. Please provide an example sprite / setup which I can reproduce your problems with.

Besides that, you may still override the default Mustache template used for rendering your stylesheet and replace the [relative positions](https://github.com/jkphl/svg-sprite/blob/master/tmpl/css/sprite.css#L7) against absolute ones (the absolute values still exist as [template variables](https://github.com/jkphl/svg-sprite/blob/master/docs/templating.md#sprite--shape-variables), e.g. `position.absolute.xy`).

Cheers, Joschi

**Comment by PeterMK85** [comment]
@jkphl hmm probably I'm missign a point here, what do you mean under *percent* is enabaling the responsivness?

Here is a good example for how the % is calculated differently **(percents at the end are pixel values)** /Open it in different browsers: http://cruft.io/rounding /

# Calculated difference 
*(On  **Windows 8.1** *Chrome 43.0.2357.81m* and *IE11.0.9600.17801*)

**Comment by jkphl** [comment]
Hi Peter,

sorry for the late reply! I'm not sure if you intentionally deleted your
latest comment, but I can't find it nowhere on GitHub anymore. Anyway, I
prepared a little pen to display what I mean with "enabling responsivity":

http://codepen.io/jkphl/pen/YXVdMX

As soon as you want to scale an SVG sprite shape embedded with
`background-image` you will have to use `background-size: 100% auto` (or
the other way round) for making the image stretch to fit your element.
With the background image positioned absolutely this will screw its
position, whereas a relatively positioned image will align nicely. Does
this make sense to you?

As far as the percent calculation is concerned: Please correct me if I'm
wrong, but I can only see sub-pixel differences, so I don't think this
is too relevant. At least it doesn't outweigh the responsivity thing ...

Cheers,
Joschi


Am 03.06.2015 um 09:18 schrieb Peter Marosi:
> @jkphl <https://github.com/jkphl> hmm probably I'm missign a point here,
> what do you mean under /percent/ is enabaling the responsivness?
> 
> Here is a good example for how the % is calculated differently
> *(percents at the end are pixel values)* /Open it in different browsers:
> http://cruft.io/rounding /
> 
> 
>   Calculated difference
> 
> /(On */Windows 8.1** /Chrome 43.0.2357.81m/ and /IE11.0.9600.17801/)
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkphl/grunt-svg-sprite/issues/52#issuecomment-108225555>.
> 


-- 
» Dipl.-Ing. Joschi Kuphal
  TYPO3 Certified Integrator
  joschi@tollwerk.de

-----------------------------------
» tollwerk® GmbH
  kommunikation . grafik . design

  Klingenhofstraße 5
  90411 Nürnberg
  Deutschland - Germany

  fon +49 (0)911 959394 - 5
  fax +49 (0)911 959394 - 7

  http://tollwerk.de
  info@tollwerk.de

  Sitz der Gesellschaft: Nürnberg
  Geschäftsführer: Dipl.-Ing. Joschi Kuphal
  Amtsgericht Nürnberg HRB 24867

-----------------------------------
» Bitte schonen Sie unsere Umwelt und drucken Sie diese Nachricht nur,
  sollte es unbedingt notwendig sein - danke!
  Please protect our environment and don't print this message unless
  you really need to - thank you!
