### ISSUE TITLE
svg-sprite 1.2.0 breaks grunt-svg-sprite

### ISSUE THREAD

**Issue by flecno** [jkphl/grunt-svg-sprite#53]
It seems the new version of svg-sprite https://github.com/jkphl/svg-sprite/releases/tag/v1.2.0 matches `^1.1.2` (https://github.com/jkphl/grunt-svg-sprite/blob/v1.1.2/package.json#L32).
The versions are not compatible:

```
Running "svg_sprite:default" (svg_sprite) task
Fatal error: ENOENT, no such file or directory '/xx/node_modules/grunt-svg-sprite/node_modules/svg-sprite/tmpl/defs/sprite.html'
```

**Comment by jkphl** [comment]
@flecno Sorry, v1.2.0 was broken. I just pushed out a new release, new grunt package following shortly. Cheers, Joschi

**Comment by flecno** [comment]
thx
