### ISSUE TITLE
Fatal error: Cannot read property 'distribute' of undefined

### ISSUE THREAD

**Issue by soultech67** [jkphl/grunt-svg-sprite#55]
I just posted the following issue (https://github.com/jkphl/svg-sprite/issues/94) at https://github.com/jkphl/svg-sprite with details about a bug we're seeing with grunt-svg-sprite / svg-sprite.

I wanted to post the info here as well so people don't spin their wheels. 

1. We reference grunt-svg-sprite as "^1.1.10" and end up with the latest after an 'npm install' on a fresh box.
2. Back in 1.1.10 grunt-svg-sprite referenced svg-sprite also as "^1.1.10" 
3. The bug seems to be in svg-sprite, so even when I modify our reference to "1.1.10" to force a pull of the old version of grunt-svg-sprite, we still end up with the latest svg-sprite module (1.2.3 right now) which has the bug. 
4. I think you've already fixed the svg-sprite reference to lock it down to an expected version in your packages.json with the "svg-sprite": "~1.2.3" declaration.

**Comment by jkphl** [comment]
You're right, the dependency confusion has already been fixed.

**Comment by jkphl** [comment]
Fixed, please see https://github.com/jkphl/svg-sprite/issues/94 for an explanation.
