### ISSUE TITLE
"Done without errors" shows when there are errors processing file.

### ISSUE THREAD

**Issue by jsr6720** [jkphl/grunt-svg-sprite#58]
See below output. I wasn't seeing a file, had to turn on logging.

Would suggest either "info" logging by default, with option of "none" or fix error message to indicate a file failed to process.

```console

C:\rtc_payx_n2a_workspace\png\ssoapps\payroll\html
Environment: isJenkins=false

Running "svg_sprite:icons" (svg_sprite) task
2015-08-03 11:38:55 - info: Created spriter instance
2015-08-03 11:38:56 - error: Skipping "tile\assets\img\warning-round-icon.svg" (Invalid SVG file (element parse error: ArgumentError: Invalid SVG file (entity not found:&ns_extend; @#[line:13,col:1]) @#[line:13,col:1]))
2015-08-03 11:38:56 - info: Compiling 12 shapes ...
2015-08-03 11:38:56 - info: Laying out «css» sprite («css» mode)
2015-08-03 11:38:56 - info: Finished «css» sprite compilation
2015-08-03 11:38:56 - info: Created 1 x SVG, 1 x LESS

? png-icons.svg (19.8 kB)
? css\png-payroll-icons.less (1.6 kB)

Done, without errors.


Execution Time (2015-09-03 15:38:55 UTC)
loading tasks             294ms  ██████████████████████████████████████████ 30%
loading grunt-svg-sprite  234ms  █████████████████████████████████ 24%
svg_sprite:icons          442ms  ██████████████████████████████████████████████████████████████ 46%
Total 970ms
```

![image](https://cloud.githubusercontent.com/assets/502432/9663650/71af1800-5233-11e5-9df4-04ece8f6096b.png)

**Comment by jkphl** [comment]
Hey @jsr6720,

thanks for this report. I agree that a failing SVG file should result in an error message regardless of the logging mode. At least it shouldn't state "Done, without errors.". However, I'd prefer not to enable logging by default, as this could produce quite some noise in cases with many SVG files ...

I'll consider this for the next release.

Cheers, Joschi

**Comment by jkphl** [comment]
As of [release 1.2.11](https://github.com/jkphl/grunt-svg-sprite/releases/tag/v1.2.11) the task will abort and dump an error message in case something goes wrong, even if logging isn't turned on.

**Comment by jsr6720** [comment]
Thank you.
