### ISSUE TITLE
wrong dimensions and color

### ISSUE THREAD

**Issue by tanmay1978** [jkphl/grunt-svg-sprite#59]
An icon of dimension 40x40 when added to sprite it renders it as 50x50

Another issue is with the color. If I have a svg icon of white when that is added to the sprite it defaults to black. But that is beacause a class is added to all the svg elements and that class is overriden for other icons in the sprite. Is that a way to eliminate the use of css styles that it applies by default?

**Comment by jkphl** [comment]
Hey @tanmay1978,

regarding the dimension issue, please post your complete configuration for the transformation.

Regarding the color: Please follow [this thread](https://github.com/jkphl/svg-sprite/issues/96) for an explanation (and possible solution).

Cheers, Joschi

**Comment by tanmay1978** [comment]
Hi the grunt config is as follow

// Make SVG sprite images from input svg icons
		svg_sprite : {
			your_target : {
				cwd			: paths.images.srcIcons,
				src         : '*.svg',
				dest        : paths.images.staticImages,
				options                 : {
					shape               : {
						spacing         : {
							padding     : 5
						}
					},
					mode                : {
						view            : {
							bust        : false,
							render      : {
								scss    : {
									dest	: '_sprite'
								}
							}
						}
					}
				}
			}
		},

**Comment by jkphl** [comment]
So the dimension increase from 40 to 50 pixels is a logical result of your `shape.spacing.padding = 5` option, as `shape.spacing.box` defaults to `"content"`. Please see the [documentation](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-spacing) for all details about this.

Did you follow the other thread regarding the CSS issue.

As I don't see any error in `svg-sprite`'s behavior here I'll close this issue for now. Please feel free to re-open it in case of any further real errors.

Cheers, Joschi

**Comment by tanmay1978** [comment]
Thanks will can confirm

**Comment by tanmay1978** [comment]
I just checked if I use shape.spacing.box then the sprites are generated with no spacing between them and still the dimensions vary by 10px

**Comment by jkphl** [comment]
What value did you set for `shape.spacing.box`?

**Comment by tanmay1978** [comment]
it was set to "content"


[image: --]

Tanmay Arun Navghare
[image: https://]about.me/tanmayarunnavghare
<https://about.me/tanmayarunnavghare?promo=email_sig>

**Comment by jkphl** [comment]
So you didn't change anything? Then, of course, the behavior wouldn't change. Again, please read [the relevant documentation section](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-spacing) to understand the available options and how to use them. Thanks.
