### ISSUE TITLE
Task runs, but not compile something

### ISSUE THREAD

**Issue by craft37** [jkphl/grunt-svg-sprite#60]
Hello.

Stunned with trouble, pleased somebody to help.
Firstly, scirpt runs only with expand:true option.
Secondly, when it even runned with no-errors, there are no compiled css neither svg-sprite.
Terminal log is clear so I just dont know what happened that task just runs in 18ms with no result.
Tried to comment options, but also no result.

Ubuntu 15.10
Node 4.1 stable

![screenshot from 2015-10-15 17-37-36](https://cloud.githubusercontent.com/assets/3589618/10516983/727a9bf0-7363-11e5-9bce-c486cd8c2732.png)

```
 svg_sprite      : {
        options     : {
            // Task-specific options go here.
        },
        icons : {
            // Target-specific file lists and/or options go here.
            expand      : true,
            cwd         : '<%= config.app %>/styles/common/.',
            src         : ['<%= config.app %>/images/icons/*.svg'],
            dest        : '<%= config.app %>/images/svg_sprite',
            // options     : {
            //     // Target-specific options
            //     symbol          : true,
            //     spacing         : {         // Add padding
            //         padding     : 10
            //   },
            // }
        },
    },

```

**Comment by jkphl** [comment]
It's probably a config problem. Please ensure 

1. that `cwd` is a valid path on your file system, and
2. that `src` is a [valid globbing pattern](http://gruntjs.com/configuring-tasks#globbing-patterns) **relative to `cwd`** matching your SVG files (e.g. `**/*.svg`).

Of course `expand` needs to be true for `cwd` to work, please see the [relevant Grunt documentation sections](http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically) for details.

Hope this helps. Cheers, Joschi

**Comment by craft37** [comment]
Now I wrote absolute path and have funny message.
```
Running "svg_sprite:icons" (svg_sprite) task
>> Source file "/*/app/images/icons/arrow_caption.svg" not found.
>> Source file "/*/app/images/icons/arrow_view_all.svg" not found.
```
So, it see filename, but not see files themeselfes.

Config is:

```
     cwd         : '.',
     src         : ['/*/app/images/icons/*.svg'],
     dest        : '/*/app/images/svg_sprite',

```

Let me descibe how I understood:
cwd - root of src dirctory
src - sources with many SVG icons
dest - place to compiled svg sprite (not necessary to write path with filename, right?)

Understand that this is kind a strange problem, but I am pretty comfortable with another grunt task dealing so I am just dont understand what kind of path could be wrong.

Thanks.

**Comment by jkphl** [comment]
I'm not sure whether `/*/app/images/icons/*.svg` is valid for the `src` property. Please try stripping off the leading `/`.

> dest - place to compiled svg sprite (not necessary to write path with filename, right?)

Right, without the filename, just a directory.

**Comment by craft37** [comment]
Joschi, I've finally compiled sprites with empty cwd!
One another question - is it possible to keep styles and sprites in different dest fodlers?
thanks!
```
            cwd         : '',
            src         : ['<%= config.app %>/images/icons/*.svg'],
            dest        : '<%= config.app %>/images/svg_sprite',
```

**Comment by jkphl** [comment]
Hey @craft37,

glad that it works for you now.

> One another question - is it possible to keep styles and sprites in different dest fodlers?

Sure! Your CSS files will be rendered to `mode.<mode>.dest`, while there's `mode.<mode>.sprite` to control the sprite location (relative to `mode.<mode>.dest`). Please see the [chapter about output destinations](https://github.com/jkphl/svg-sprite#output-destinations) for more details.

Cheers, Joschi

**Comment by craft37** [comment]
Sorry, I dont got from docs - could I configure separate dests from grunt or I need to use it in 'manual '  way?

**Comment by jkphl** [comment]
All the configuration options are shared between the Grunt, Gulp and Node version of *svg-sprite*. You may also always use the [online kickstarter](http://jkphl.github.io/svg-sprite) to create your config.

**Comment by craft37** [comment]
Ow, nice option witch config-kickstarter.
thank you.
