### ISSUE TITLE
Feature request: change svg fill to currentColor optionally

### ISSUE THREAD

**Issue by craft37** [jkphl/grunt-svg-sprite#61]
It will be nice if script could optionally change svg fill to 'currentColor', so it will be possible to change svg color easy with css styles.

**Comment by jkphl** [comment]
I'm sorry but it's definitely out of *svg-sprite*'s scope to alter the SVG files, at least on a builtin support level. However, you have several options for this:

1. Prepare your SVG files **before** processing them with *svg-sprite*.
2. Use one of the many available [SVG packages](https://www.npmjs.com/search?q=svg) out there to pre- or post-process the SVG files.
3. Use *svg-sprite*'s [shape](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-transformations) or [post-processing support](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#svg-sprite-customization) for writing code doing what you desire.

Cheers, Joschi

**Comment by craft37** [comment]
Yep, thats clear now.
Thanks for expanded answer. Nice day to you.
