### ISSUE TITLE
SVGSpriter.add: "..\etc\file.svg" is not the local part of "d:\project\etc\file.svg

### ISSUE THREAD

**Issue by ottomen** [jkphl/grunt-svg-sprite#62]
Hi!

I added svg sprite task to the Grunt. Here it is:
```
svg_sprite: {
            options: {
                // Task-specific options go here.
            },
            your_target: {
                src: ['../../images/*.svg'],
                dest: '../../images/dir',
                options: {
                    // Target-specific options
                }
            },
        },
```
All folder nestings are correct, but i get this error: "SVGSpriter.add: "..\..\images\close-cross-black.svg is not the local part of "d:\some_folders\repository\assets\guidelines\images\close-cross-black.svg". What can be wrong with my grunt task configuration?

**Comment by jkphl** [comment]
Hey @ottomen,

there's nothing wrong with your configuration — it was a restriction that source SVG was not allowed to be located outside the current (working) directory. The latest release fixes this, your configuration should run now! Please let me know if you still encounter errors.

Cheers, Joschi
