### ISSUE TITLE
Simple example doesnt work

### ISSUE THREAD

**Issue by jvr84** [jkphl/grunt-svg-sprite#63]
```js
your_target: {
    src         : ['path/to/assets/**/*.svg'],
    dest        : 'path/to/css/dir',
    options     : {
        // Target-specific options
    }
}
```

This doesnt work, i had to add the mode to the target specific options to make it work

like this:
```js
your_target: {
    src         : ['path/to/assets/**/*.svg'],
    dest        : 'path/to/css/dir',
    options     : {
          // Target-specific options
          mode	: {
                  css		: {		// Activate the «css» mode
                            render	: {
                                    css	: true	// Activate CSS output (with default options)
                            }
                   }
           }
     }
}
```

**Comment by jkphl** [comment]
Thanks for taking the time to work with *grunt-svg-sprite*!

The section you are quoting is not a full-featured usage example but serves the purpose of explaining the general structure of a Grunt task for *svg-sprite*. For working usage examples please have a look at the [like-named section](https://github.com/jkphl/grunt-svg-sprite#usage-examples).

Cheers, Joschi
