### ISSUE TITLE
"SVG Stacks" link in README is a 404

### ISSUE THREAD

**Issue by henrahmagix** [jkphl/grunt-svg-sprite#69]
Is there another page of similar helpfulness?

http://simurai.com/blog/2012/04/02/svg-stacks/

**Comment by jkphl** [comment]
@henrahmagix Thanks for reporting. I'll update the docs and use the [archive.org link](https://web.archive.org/web/20160120092300/http://simurai.com/blog/2012/04/02/svg-stacks/). ;)

**Comment by henrahmagix** [comment]
Thanks!
