### ISSUE TITLE
SVG sprite - remove random string from filename

### ISSUE THREAD

**Issue by contactjoelg** [jkphl/grunt-svg-sprite#73]
How can I remove random string from filename?

The following currently generates 'sprite-[########].svg'
```
mode            : {
    css         : {
        "sprite"     : "sprite.svg"
    }
}
```
I would like to just generate 'sprite.svg'.

**Comment by jkphl** [comment]
Please toggle the `mode.<mode>.bust` option to disable cache busting (see [common configuration options](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties)).

**Comment by contactjoelg** [comment]
Thank you Joschi, it works now.
