### ISSUE TITLE
render specified 'folder/', not default 'css/'

### ISSUE THREAD

**Issue by contactjoelg** [jkphl/grunt-svg-sprite#74]
How can I avoid the rendering the default 'css/'? instead, I would like to just render the specified 'images/': 
```
svg_sprite  : {
    your_target : {
        cwd     : 'src/',
        src : ['src/*.svg'],
        dest    : 'images/'
    }
}

```

**Comment by jkphl** [comment]
Please read the [documentation about output destinations](https://github.com/jkphl/svg-sprite#output-destinations) to understand the different options. Basically you will have to set `dest` to `"images"` and `mode.<mode>.dest` to `"."`.

**Comment by contactjoelg** [comment]
Thank you Joschi, it works now.
