### ISSUE TITLE
Warning: Object #<Object> has no method 'isAbsolute' Use

### ISSUE THREAD

**Issue by gazpachu** [jkphl/grunt-svg-sprite#75]
Recently I started to get this error. Any idea of what this could be?

```
`Running "svg_sprite:basic" (svg_sprite) task
Warning: Object #<Object> has no method 'isAbsolute' Use --force to continue.

Aborted due to warnings.`
```

**Comment by jkphl** [comment]
@gazpachu `path.isAbsolute()` should be [available as of Node v.0.11.2](https://nodejs.org/api/path.html#path_path_isabsolute_path). Which version are you using?

**Comment by jkphl** [comment]
@gazpachu Oh, could you also post the code you use to add your source SVG files to the spriter?

**Comment by gazpachu** [comment]
That was the issue. I was using an old version. Thx
