### ISSUE TITLE
SVG Sprite CSS generation issue

### ISSUE THREAD

**Issue by yamsoft** [jkphl/grunt-svg-sprite#77]
Hi...
Just wanted to ask if it is possible to get the pixel position of an individual svg icon from the generated sprite?

**Comment by jkphl** [comment]
Please specify what you mean with "get" the pixel position. At which stage, using which technology? During the generation of the sprite (Mustache template rendering) the absolute positions are available as template variables (please see the templating documentation for details). After the sprite is generated, it is up to you to parse / examine the sprite and extract the positions with a technology of your choice. It's out of svg-sprite's scope then.
