### ISSUE TITLE
Warning: Object  has no method 'isAbsolute'

### ISSUE THREAD

**Issue by taunoha** [jkphl/grunt-svg-sprite#78]
I'm getting this warning:
```
Running "svg_sprite:basic" (svg_sprite) task
Warning: Object #<Object> has no method 'isAbsolute' Use --force to continue.
```

Config:
```
basic: {
      expand: false,
      src: ['assets/src/gfx/icons/*.svg'],
      dest: ''
}
```

Am I missing something?

**Comment by jkphl** [comment]
@taunoha I suppose you're running an old Node.js version that isn't supported any longer for quite a while now. Please see https://github.com/jkphl/grunt-svg-sprite/issues/75
