### ISSUE TITLE
Multiple output sprites?

### ISSUE THREAD

**Issue by ogonkov** [jkphl/grunt-svg-sprite#83]
Is there a way to have _single_ task with multiple output?

What i'm trying to do is convert such folders structure:
```
projectA
  componentA
    a.svg
    b.svg
  componentB
    c.svg
    d.svg
projectB
  componentA
    a.svg
    b.svg
  componentB
    c.svg
    d.svg
```

to

```
projectA
  componentA
    sprite.scss
  componentB
    sprite.scss
projectB
  componentA
    sprite.scss
  componentB
    sprite.scss
dist
  projectA
    componentA
      sprite.svg
    componentB
      sprite.svg

  projectB
    componentA
      sprite.svg
    componentB
      sprite.svg
```

Folders structure is not that important, i stuck trying to have multiple sprites.

I can write some bootstrap task/function that would generate task config for component, but may be there is more simple way to have similar output with multiple sprites?

**Comment by jkphl** [comment]
@ogonkov Unfortunately, the answer is simple: No, at the moment there's no way to have a *single* task creating multiple sprites (regardles of the folder structure).
